# Generated by Django 5.2.15 on 2026-06-25 12:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Tên dịch vụ')),
                ('category', models.CharField(max_length=100, verbose_name='Chuyên khoa')),
                ('duration_min', models.IntegerField(default=30, verbose_name='Thời lượng (phút)')),
                ('price', models.IntegerField(verbose_name='Giá (nghìn VNĐ)')),
                ('description', models.TextField(blank=True, default='', verbose_name='Mô tả')),
                ('doctor_name', models.CharField(max_length=100, verbose_name='Bác sĩ phụ trách')),
            ],
            options={
                'verbose_name': 'Dịch vụ y tế',
                'verbose_name_plural': 'Dịch vụ y tế',
            },
        ),
        migrations.CreateModel(
            name='TimeSlot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.CharField(max_length=50, unique=True, verbose_name='Khung giờ')),
                ('is_available', models.BooleanField(default=True, verbose_name='Có sẵn')),
            ],
            options={
                'verbose_name': 'Khung giờ khám',
                'verbose_name_plural': 'Khung giờ khám',
            },
        ),
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Ngày khám')),
                ('symptoms', models.TextField(verbose_name='Triệu chứng lâm sàng')),
                ('status', models.CharField(choices=[('pending', 'Chờ xác nhận'), ('confirmed', 'Đã duyệt'), ('cancelled', 'Đã hủy')], default='pending', max_length=10, verbose_name='Trạng thái')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Thời gian tạo')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appointments', to=settings.AUTH_USER_MODEL, verbose_name='Bệnh nhân')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appointments', to='authentication.service', verbose_name='Dịch vụ')),
                ('time_slot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appointments', to='authentication.timeslot', verbose_name='Khung giờ')),
            ],
            options={
                'verbose_name': 'Lịch hẹn khám',
                'verbose_name_plural': 'Lịch hẹn khám',
                'ordering': ['-created_at'],
            },
        ),
    ]
