# Generated by Django 5.2 on 2026-06-26 02:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_service_timeslot_appointment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='auth_appointments', to=settings.AUTH_USER_MODEL, verbose_name='Bệnh nhân'),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='service',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='auth_appointments', to='authentication.service', verbose_name='Dịch vụ'),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='time_slot',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='auth_appointments', to='authentication.timeslot', verbose_name='Khung giờ'),
        ),
    ]
