# Generated by Django 5.1.1 on 2026-06-24 15:03

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinic_catalog', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='medicalservice',
            options={'ordering': ['-created_at'], 'verbose_name': 'Dịch vụ Y tế', 'verbose_name_plural': 'Dịch vụ Y tế'},
        ),
        migrations.AlterModelOptions(
            name='timeslot',
            options={'ordering': ['start_time'], 'verbose_name': 'Khung giờ khám', 'verbose_name_plural': 'Khung giờ khám'},
        ),
        migrations.AddField(
            model_name='medicalservice',
            name='category',
            field=models.CharField(default='General', max_length=100, verbose_name='Danh mục'),
        ),
        migrations.AddField(
            model_name='medicalservice',
            name='doctor_name',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Tên bác sĩ'),
        ),
        migrations.AddField(
            model_name='medicalservice',
            name='duration_minutes',
            field=models.IntegerField(default=30, verbose_name='Thời lượng (phút)'),
        ),
        migrations.AddField(
            model_name='medicalservice',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Ngày cập nhật'),
        ),
        migrations.AddField(
            model_name='timeslot',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Ngày tạo'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='timeslot',
            name='is_available',
            field=models.BooleanField(default=True, verbose_name='Có sẵn'),
        ),
        migrations.AlterField(
            model_name='medicalservice',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Ngày tạo'),
        ),
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('appointment_date', models.DateField(verbose_name='Ngày khám')),
                ('symptoms', models.TextField(blank=True, default='', verbose_name='Triệu chứng')),
                ('notes', models.TextField(blank=True, default='', verbose_name='Ghi chú')),
                ('status', models.CharField(choices=[('pending', 'Chờ xác nhận'), ('confirmed', 'Đã xác nhận'), ('completed', 'Hoàn thành'), ('cancelled', 'Hủy lịch')], default='pending', max_length=20, verbose_name='Trạng thái')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Ngày đặt')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Cập nhật lần cuối')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appointments', to=settings.AUTH_USER_MODEL, verbose_name='Bệnh nhân')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appointments', to='clinic_catalog.medicalservice', verbose_name='Dịch vụ')),
                ('time_slot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appointments', to='clinic_catalog.timeslot', verbose_name='Khung giờ')),
            ],
            options={
                'verbose_name': 'Lịch hẹn khám',
                'verbose_name_plural': 'Lịch hẹn khám',
                'ordering': ['-appointment_date'],
            },
        ),
    ]
