# Generated by Django 5.2.15 on 2026-06-23 05:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MedicalService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Tên dịch vụ')),
                ('category', models.CharField(max_length=100, verbose_name='Chuyên khoa / Danh mục')),
                ('duration_min', models.IntegerField(default=30, verbose_name='Thời lượng khám (phút)')),
                ('price', models.IntegerField(verbose_name='Giá dịch vụ (USD hoặc VNĐ)')),
                ('doctor_name', models.CharField(max_length=100, verbose_name='Tên bác sĩ phụ trách')),
                ('description', models.TextField(blank=True, default='', verbose_name='Mô tả dịch vụ')),
            ],
            options={
                'verbose_name': 'Dịch vụ y tế',
                'verbose_name_plural': 'Dịch vụ y tế',
                'ordering': ['category', 'name'],
            },
        ),
        migrations.CreateModel(
            name='TimeSlot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.CharField(max_length=50, unique=True, verbose_name='Khung giờ (VD: 08:00 - 09:00)')),
                ('is_available', models.BooleanField(default=True, verbose_name='Còn trống')),
            ],
            options={
                'verbose_name': 'Khung giờ khám',
                'verbose_name_plural': 'Khung giờ khám',
                'ordering': ['time'],
            },
        ),
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patient_name', models.CharField(max_length=150, verbose_name='Họ tên bệnh nhân')),
                ('patient_phone', models.CharField(max_length=20, verbose_name='Số điện thoại')),
                ('service_name', models.CharField(blank=True, max_length=200, verbose_name='Tên dịch vụ (lưu vết)')),
                ('doctor_name', models.CharField(blank=True, max_length=100, verbose_name='Tên bác sĩ (lưu vết)')),
                ('date', models.DateField(verbose_name='Ngày khám')),
                ('time_slot', models.CharField(max_length=50, verbose_name='Khung giờ khám')),
                ('symptoms', models.TextField(blank=True, default='', verbose_name='Triệu chứng/Mô tả bệnh')),
                ('status', models.CharField(choices=[('pending', 'Chờ duyệt'), ('confirmed', 'Đã xác nhận'), ('cancelled', 'Đã hủy')], default='pending', max_length=15, verbose_name='Trạng thái lịch hẹn')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Thời gian tạo')),
                ('patient', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='appointments', to=settings.AUTH_USER_MODEL, verbose_name='Bệnh nhân (Tài khoản)')),
                ('service', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='appointments', to='clinic.medicalservice', verbose_name='Dịch vụ khám')),
            ],
            options={
                'verbose_name': 'Lịch hẹn',
                'verbose_name_plural': 'Lịch hẹn',
                'ordering': ['-date', 'time_slot'],
            },
        ),
    ]
